name: MSD
dependencies:
  - pip
  - python=3.6
  - future
  - pip:
    - numpy==1.15.1
    - tensorflow-gpu==1.11.0
    - scikit-image==0.14.0
    - scikit-learn==0.20.0
    - jupyter==1.0.0
    - flake8
    - pytest
    - autopep8
    - SimpleITK==1.1.0
    - pylint
    - tqdm
    - pyyaml
    - matplotlib
    - pip==18.0